// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArx9HSS-_A2XApZuxQEmvgoFvI5IFzf54',
    appId: '1:689983993331:web:e82f4760b3f3d9b3ee8e86',
    messagingSenderId: '689983993331',
    projectId: 'education-a7662',
    authDomain: 'education-a7662.firebaseapp.com',
    storageBucket: 'education-a7662.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMqWVk29W7NICkhT8jnCeMsDo4XhKB5-0',
    appId: '1:689983993331:android:c9ac1f1cf599a457ee8e86',
    messagingSenderId: '689983993331',
    projectId: 'education-a7662',
    storageBucket: 'education-a7662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_rEqu2WnKzQHBMvgvbqz6VX3BsZIN68E',
    appId: '1:689983993331:ios:740da6d979deb34aee8e86',
    messagingSenderId: '689983993331',
    projectId: 'education-a7662',
    storageBucket: 'education-a7662.appspot.com',
    iosBundleId: 'com.example.educationadmin',
  );
}
